package cli

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/badboy1981/Nestify/internal/analyzer"
	"github.com/badboy1981/Nestify/internal/pathutil"
	"github.com/badboy1981/Nestify/internal/scanner"
	"github.com/badboy1981/Nestify/internal/treeprinter"
)

func runContextCmd() {
	cmd := flag.NewFlagSet("context", flag.ExitOnError)
	path := cmd.String("path", ".", "Project path for context report")
	depth := cmd.Int("depth", 0, "Maximum directory depth to include (0 for unlimited)")
	prompt := cmd.String("prompt", "", "Prompt template name or custom instruction text")

	cmd.IntVar(depth, "d", 0, "Maximum directory depth to include (shorthand)")
	cmd.StringVar(prompt, "p", "", "Prompt template name or custom instruction text (shorthand)")

	cmd.Parse(os.Args[2:])

	targetPath := *path
	if targetPath == "." && len(cmd.Args()) > 0 {
		targetPath = cmd.Args()[0]
	}

	fmt.Println("🤖 Generating unified AI Context Report...")

	normPath := pathutil.NormalizeForOS(targetPath)

	nodes, err := scanner.Scan(normPath, false, *depth)
	if err != nil {
		fmt.Printf("❌ Scan error: %v\n", err)
		return
	}

	if len(nodes) == 0 {
		fmt.Println("⚠️ No files found to analyze.")
		return
	}

	absPath, _ := filepath.Abs(normPath)
	projectName := filepath.Base(absPath)
	if projectName == "" || projectName == "." || projectName == "/" || projectName == "\\" {
		projectName = "project"
	}

	if len(nodes) > 0 && nodes[0].Name == "." {
		nodes[0].Name = projectName
	}

	metricsReport := analyzer.AnalyzeSkeleton(nodes)

	treeContent := "## 🌲 Project Directory Tree\n\n```text\n"
	for _, node := range nodes {
		treeContent += treeprinter.GetTreeString(&node)
	}
	treeContent += "```\n"

	depthStr := "Unlimited"
	if *depth > 0 {
		depthStr = fmt.Sprintf("%d", *depth)
	}

	// Resolve optional injected prompt text.
	promptHeader := getPromptContent(*prompt)

	fullContext := ""
	if promptHeader != "" {
		fullContext += "# 💬 AI Task & Instructions\n\n"
		fullContext += promptHeader + "\n\n---\n\n"
	}

	fullContext += "# 🤖 Project Context for AI Analysis\n\n"
	fullContext += fmt.Sprintf("Generated by **Nestify** on %s | **Scan Depth:** %s\n\n", time.Now().Format("2006-01-02 15:04:05"), depthStr)
	fullContext += metricsReport + "\n\n---\n\n"
	fullContext += treeContent

	reportDir := pathutil.NormalizeForOS("Nestify-Report")
	if err := os.MkdirAll(reportDir, 0755); err != nil {
		fmt.Printf("❌ Failed to create report directory: %v\n", err)
		return
	}

	outputPath := filepath.Join(reportDir, "ai_context_report.md")
	err = os.WriteFile(outputPath, []byte(fullContext), 0644)
	if err != nil {
		fmt.Printf("❌ Failed to save AI Context report: %v\n", err)
		return
	}

	fmt.Println("✅ AI Context report generated successfully!")
	if promptHeader != "" {
		fmt.Println("💡 Prompt instructions were added to the top of the report.")
	}
	fmt.Printf("📄 Ready to copy/paste into an LLM: %s\n\n", outputPath)
}
