package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/badboy1981/Nestify/internal/analyzer"
	"github.com/badboy1981/Nestify/internal/pathutil"
	"github.com/badboy1981/Nestify/internal/scanner"
	"github.com/badboy1981/Nestify/internal/treeprinter"
)

func runContextCmd() {
	targetPath := "."
	if len(os.Args) > 2 {
		targetPath = os.Args[2]
	}

	fmt.Println("🤖 در حال تولید گزارش جامع پروپت هوش مصنوعی (AI Context Report)...")

	normPath := pathutil.NormalizeForOS(targetPath)

	// ۱. اسکن کامل با اعمال فیلترهای ignore
	nodes, err := scanner.Scan(normPath, false)
	if err != nil {
		fmt.Printf("❌ خطا در اسکن مسیر: %v\n", err)
		return
	}

	if len(nodes) == 0 {
		fmt.Println("⚠️ هیچ فایلی برای تحلیل پیدا نشد.")
		return
	}

	// اصلاح نام نود ریشه
	absPath, _ := filepath.Abs(normPath)
	projectName := filepath.Base(absPath)
	if projectName == "" || projectName == "." || projectName == "/" || projectName == "\\" {
		projectName = "project"
	}

	if len(nodes) > 0 && nodes[0].Name == "." {
		nodes[0].Name = projectName
	}

	// ۲. دریافت گزارش متریكس و زبان‌ها
	metricsReport := analyzer.AnalyzeSkeleton(nodes)

	// ۳. ساخت ساختار درختی پروژه
	treeContent := "## 🌲 Project Directory Tree\n\n```text\n"
	for _, node := range nodes {
		treeContent += treeprinter.GetTreeString(&node)
	}
	treeContent += "```\n"

	// ۴. ترکیب هر دو گزارش در یک فایل یکپارچه
	fullContext := "# 🤖 Project Context for AI Analysis\n\n"
	fullContext += fmt.Sprintf("Generated by **Nestify** on %s\n\n", time.Now().Format("2006-01-02 15:04:05"))
	fullContext += metricsReport + "\n\n---\n\n"
	fullContext += treeContent

	// ۵. ذخیره در پوشه گزارشات
	reportDir := pathutil.NormalizeForOS("Nestify-Report")
	if err := os.MkdirAll(reportDir, 0755); err != nil {
		fmt.Printf("❌ خطا در ایجاد پوشه گزارشات: %v\n", err)
		return
	}

	outputPath := filepath.Join(reportDir, "ai_context_report.md")
	err = os.WriteFile(outputPath, []byte(fullContext), 0644)
	if err != nil {
		fmt.Printf("❌ خطا در ذخیره گزارش AI Context: %v\n", err)
		return
	}

	fmt.Println("✅ گزارش جامع هوش مصنوعی با موفقیت ساخته شد!")
	fmt.Printf("📄 فایل آماده برای Copy/Paste در هوش مصنوعی: %s\n\n", outputPath)
}
