package cli

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/badboy1981/Nestify/internal/pathutil"
	"github.com/badboy1981/Nestify/internal/scanner"
	"github.com/badboy1981/Nestify/internal/treeprinter"
	"github.com/badboy1981/Nestify/internal/types"
)

func runScanCmd() {
	cmd := flag.NewFlagSet("scan", flag.ExitOnError)
	path := cmd.String("path", ".", "Project path to scan")
	tree := cmd.Bool("tree", false, "Generate tree-view report")
	foldersOnly := cmd.Bool("folders-only", false, "Scan folders only")

	depth := cmd.Int("depth", 0, "Maximum directory depth to scan (0 for unlimited)")
	cmd.IntVar(depth, "d", 0, "Maximum directory depth to scan (shorthand)")

	cmd.Parse(os.Args[2:])

	cleanPath := pathutil.NormalizeForOS(*path)
	runScan(cleanPath, *tree, *foldersOnly, *depth)
}

func runScan(cleanPath string, printTree bool, foldersOnly bool, maxDepth int) {
	rootNodes, err := scanner.Scan(cleanPath, foldersOnly, maxDepth)
	if err != nil {
		fmt.Printf("❌ Scan error: %v\n", err)
		return
	}

	absPath, _ := filepath.Abs(cleanPath)
	targetName := filepath.Base(absPath)
	if targetName == "" || targetName == "." || targetName == "/" || targetName == "\\" {
		targetName = "project"
	}

	if len(rootNodes) > 0 && rootNodes[0].Name == "." {
		rootNodes[0].Name = targetName
	}

	// When --path points at a subdirectory of the current working directory,
	// wrap the scanned tree in ancestor folders from cwd down to the target
	// so the report shows full path context (only the target's contents are expanded).
	cwd, err := os.Getwd()
	if err == nil {
		rootNodes = wrapWithCwdAncestors(rootNodes, cwd, absPath)
	}

	projectName := targetName
	if len(rootNodes) > 0 {
		projectName = rootNodes[0].Name
	}

	reportDir := pathutil.NormalizeForOS("Nestify-Report")
	if err := os.MkdirAll(reportDir, 0755); err != nil {
		fmt.Printf("❌ Error creating report directory: %v\n", err)
		return
	}

	timestamp := time.Now().Format("20060102_150405")
	baseFileName := fmt.Sprintf("%s_%s", targetName, timestamp)

	jsonPath := filepath.Join(reportDir, baseFileName+".json")
	mdPath := filepath.Join(reportDir, baseFileName+".md")

	if err := saveJSON(rootNodes, jsonPath); err != nil {
		fmt.Printf("❌ JSON save error: %v\n", err)
	}

	if printTree {
		if err := saveTree(rootNodes, mdPath, projectName, maxDepth); err != nil {
			fmt.Printf("❌ Markdown save error: %v\n", err)
		}
	}

	fmt.Println("\n✅ Scan completed successfully!")
	fmt.Printf("📂 Reports saved in: %s\n", reportDir)
	fmt.Printf("   📄 JSON: %s\n", filepath.Base(jsonPath))
	if printTree {
		fmt.Printf("   📄 Markdown: %s\n", filepath.Base(mdPath))
	}
}

// wrapWithCwdAncestors rebuilds the node tree so it starts at the current
// working directory name and chains intermediate folders down to the scanned
// target. Sibling folders along the path are not included—only the path to
// the target and the target's scanned children.
func wrapWithCwdAncestors(nodes []types.Node, cwd, targetAbs string) []types.Node {
	if len(nodes) == 0 {
		return nodes
	}

	cwdAbs, err := filepath.Abs(cwd)
	if err != nil {
		return nodes
	}
	cwdAbs = filepath.Clean(cwdAbs)
	targetAbs = filepath.Clean(targetAbs)

	if cwdAbs == targetAbs {
		return nodes
	}

	rel, err := filepath.Rel(cwdAbs, targetAbs)
	if err != nil {
		return nodes
	}
	// Target is outside cwd (e.g. absolute path elsewhere).
	if rel == ".." || strings.HasPrefix(rel, ".."+string(os.PathSeparator)) {
		return nodes
	}

	rel = pathutil.ToStandardPath(rel)
	if rel == "" || rel == "." {
		return nodes
	}

	parts := strings.Split(rel, "/")
	filtered := make([]string, 0, len(parts))
	for _, p := range parts {
		if p != "" && p != "." {
			filtered = append(filtered, p)
		}
	}
	if len(filtered) == 0 {
		return nodes
	}

	current := nodes[0]
	// Walk from parent of target up to the first path segment under cwd.
	for i := len(filtered) - 2; i >= 0; i-- {
		current = types.Node{
			Name:     filtered[i],
			Type:     "folder",
			Children: []types.Node{current},
		}
	}

	cwdName := filepath.Base(cwdAbs)
	if cwdName == "" || cwdName == "." || cwdName == "/" || cwdName == "\\" {
		cwdName = "project"
	}

	root := types.Node{
		Name:     cwdName,
		Type:     "folder",
		Children: []types.Node{current},
	}
	return []types.Node{root}
}

func saveJSON(data interface{}, targetPath string) error {
	file, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(targetPath, file, 0644)
}

// saveTree writes a Markdown tree report including scan depth metadata.
func saveTree(nodes []types.Node, targetPath string, projectName string, maxDepth int) error {
	depthStr := "Unlimited"
	if maxDepth > 0 {
		depthStr = fmt.Sprintf("%d", maxDepth)
	}

	content := fmt.Sprintf("# Project Structure: %s\n\n", projectName)
	content += fmt.Sprintf("Generated by **Nestify** on %s | **Scan Depth:** %s\n\n", time.Now().Format("2006-01-02 15:04:05"), depthStr)
	content += "```text\n"

	for _, node := range nodes {
		content += treeprinter.GetTreeString(&node)
	}

	content += "```\n"

	return os.WriteFile(targetPath, []byte(content), 0644)
}
