package cli

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/badboy1981/Nestify/internal/pathutil"
	"github.com/badboy1981/Nestify/internal/scanner"
	"github.com/badboy1981/Nestify/internal/treeprinter"
	"github.com/badboy1981/Nestify/internal/types"
)

func runScanCmd() {
	cmd := flag.NewFlagSet("scan", flag.ExitOnError)
	path := cmd.String("path", ".", "Project path to scan")
	tree := cmd.Bool("tree", false, "Generate tree-view report")
	foldersOnly := cmd.Bool("folders-only", false, "Scan folders only")

	depth := cmd.Int("depth", 0, "Maximum directory depth to scan (0 for unlimited)")
	cmd.IntVar(depth, "d", 0, "Maximum directory depth to scan (shorthand)")

	cmd.Parse(os.Args[2:])

	cleanPath := pathutil.NormalizeForOS(*path)
	runScan(cleanPath, *tree, *foldersOnly, *depth)
}

func runScan(cleanPath string, printTree bool, foldersOnly bool, maxDepth int) {
	rootNodes, err := scanner.Scan(cleanPath, foldersOnly, maxDepth)
	if err != nil {
		fmt.Printf("❌ Scan error: %v\n", err)
		return
	}

	absPath, _ := filepath.Abs(cleanPath)
	projectName := filepath.Base(absPath)

	if projectName == "" || projectName == "." || projectName == "/" || projectName == "\\" {
		projectName = "project"
	}

	if len(rootNodes) > 0 && rootNodes[0].Name == "." {
		rootNodes[0].Name = projectName
	}

	reportDir := pathutil.NormalizeForOS("Nestify-Report")
	if err := os.MkdirAll(reportDir, 0755); err != nil {
		fmt.Printf("❌ Error creating report directory: %v\n", err)
		return
	}

	timestamp := time.Now().Format("20060102_150405")
	baseFileName := fmt.Sprintf("%s_%s", projectName, timestamp)

	jsonPath := filepath.Join(reportDir, baseFileName+".json")
	mdPath := filepath.Join(reportDir, baseFileName+".md")

	if err := saveJSON(rootNodes, jsonPath); err != nil {
		fmt.Printf("❌ JSON save error: %v\n", err)
	}

	if printTree {
		if err := saveTree(rootNodes, mdPath, projectName, maxDepth); err != nil {
			fmt.Printf("❌ Markdown save error: %v\n", err)
		}
	}

	fmt.Println("\n✅ Scan completed successfully!")
	fmt.Printf("📂 Reports saved in: %s\n", reportDir)
	fmt.Printf("   📄 JSON: %s\n", filepath.Base(jsonPath))
	if printTree {
		fmt.Printf("   📄 Markdown: %s\n", filepath.Base(mdPath))
	}
}

func saveJSON(data interface{}, targetPath string) error {
	file, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(targetPath, file, 0644)
}

// تابع تغییر یافته جهت اضافه کردن اطلاعات عمق اسکن در فایل
func saveTree(nodes []types.Node, targetPath string, projectName string, maxDepth int) error {
	depthStr := "Unlimited"
	if maxDepth > 0 {
		depthStr = fmt.Sprintf("%d", maxDepth)
	}

	content := fmt.Sprintf("# Project Structure: %s\n\n", projectName)
	content += fmt.Sprintf("Generated by **Nestify** on %s | **Scan Depth:** %s\n\n", time.Now().Format("2006-01-02 15:04:05"), depthStr)
	content += "```text\n"

	for _, node := range nodes {
		content += treeprinter.GetTreeString(&node)
	}

	content += "```\n"

	return os.WriteFile(targetPath, []byte(content), 0644)
}
