package cli

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/badboy1981/Nestify/internal/scanner"
	"github.com/badboy1981/Nestify/internal/treeprinter"
	"github.com/badboy1981/Nestify/internal/types"
)

func runScanCmd() {
	cmd := flag.NewFlagSet("scan", flag.ExitOnError)
	path := cmd.String("path", ".", "Project path to scan")
	tree := cmd.Bool("tree", false, "Generate tree-view report")
	foldersOnly := cmd.Bool("folders-only", false, "Scan folders only")

	cmd.Parse(os.Args[2:])

	cleanPath := NormalizePath(*path)
	runScan(cleanPath, *tree, *foldersOnly)
}

func runScan(cleanPath string, printTree bool, foldersOnly bool) {
	rootNodes, err := scanner.Scan(cleanPath, foldersOnly)
	if err != nil {
		fmt.Printf("❌ Scan error: %v\n", err)
		return
	}

	// ۱. به دست آوردن نام واقعی پوشه پروژه به جای "."
	absPath, _ := filepath.Abs(cleanPath)
	projectName := filepath.Base(absPath)

	// اگر به هر دلیلی نام خالی بود یا ریشه درایو بود
	if projectName == "" || projectName == "." || projectName == "/" || projectName == "\\" {
		projectName = "project"
	}

	// ۲. اصلاح نام نود ریشه در خروجی (بسیار مهم)
	// اسکنر معمولاً یک نود ریشه برمی‌گرداند که نامش "." است.
	if len(rootNodes) > 0 && rootNodes[0].Name == "." {
		rootNodes[0].Name = projectName
	}

	// ۳. مدیریت پوشه گزارشات
	reportDir := NormalizePath("reports")
	if err := os.MkdirAll(reportDir, 0755); err != nil {
		fmt.Printf("❌ Error creating report directory: %v\n", err)
		return
	}

	// ۳. نام‌گذاری با زمان دقیق
	timestamp := time.Now().Format("20060102_150405")
	baseFileName := fmt.Sprintf("%s_%s", projectName, timestamp)

	jsonPath := filepath.Join(reportDir, baseFileName+".json")
	mdPath := filepath.Join(reportDir, baseFileName+".md")

	// ذخیره JSON
	if err := saveJSON(rootNodes, jsonPath); err != nil {
		fmt.Printf("❌ JSON save error: %v\n", err)
	}

	// ذخیره Markdown (فقط اگر فلگ tree-- زده شده باشد)
	if printTree {
		if err := saveTree(rootNodes, mdPath, projectName); err != nil {
			fmt.Printf("❌ Markdown save error: %v\n", err)
		}
	}

	fmt.Println("\n✅ Scan completed successfully!")
	fmt.Printf("📂 Reports saved in: %s\n", reportDir)
	fmt.Printf("   📄 JSON: %s\n", filepath.Base(jsonPath))
	if printTree {
		fmt.Printf("   📄 Markdown: %s\n", filepath.Base(mdPath))
	}
}

// تابع کمکی برای ذخیره JSON
func saveJSON(data interface{}, targetPath string) error {
	file, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(targetPath, file, 0644)
}

// تابع کمکی برای ذخیره ساختار درختی در فایل Markdown
func saveTree(nodes []types.Node, targetPath string, projectName string) error {
	content := fmt.Sprintf("# Project Structure: %s\n\n", projectName)
	content += "Generated by **Nestify** on " + time.Now().Format("2006-01-02 15:04:05") + "\n\n"
	content += "```text\n"

	// اصلاح این بخش: پیمایش روی نودهای ریشه و تبدیل آن‌ها به رشته
	for _, node := range nodes {
		content += treeprinter.GetTreeString(&node)
	}

	content += "```\n"

	return os.WriteFile(targetPath, []byte(content), 0644)
}
